version: '3'

services:
  clickhouse:
    image: yandex/clickhouse-server:22.1.3.7
    container_name: clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # 运行日志
      - ./log:/var/log/clickhouse-server
      # 数据持久
      - ./data:/var/lib/clickhouse:rw
      # 默认配置
      - ./conf/docker_related_config.xml:/etc/clickhouse-server/config.d/docker_related_config.xml:rw
      - ./conf/config.xml:/etc/clickhouse-server/config.xml:rw
      - ./conf/users.xml:/etc/clickhouse-server/users.xml:rw
