apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-ingress
  namespace: ruoyi
spec:
  ingressClassName: nginx
  rules:
    - host: lingero.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
    - host: api.lingero.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ruoyi-service
                port:
                  number: 8080
    - host: blog.lingero.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: halo-service
                port:
                  number: 8090
